name: Run Javascript Tests

on:
  push:
    branches: [ main ]
    paths:
    - '401/**'
  pull_request:
    branches: [ main ]
    paths:
    - '401/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd 401
        npm i
        npm test
      env:
        CI: true
